//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCaffe.imagedb
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabelBoost
    {
        public int ID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> ActiveLabel { get; set; }
        public Nullable<decimal> Boost { get; set; }
        public Nullable<int> SourceID { get; set; }
    }
}
