//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCaffe.imagedb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawImageMean
    {
        public int ID { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Channels { get; set; }
        public byte[] Data { get; set; }
        public Nullable<bool> Encoded { get; set; }
        public Nullable<int> SourceID { get; set; }
    }
}
