//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCaffe.layers.python.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyCaffe.layers.python.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import clr
        ///
        ///import System
        ///from System import Array, Single
        ///import ctypes
        ///
        ///from tqdm import tqdm
        ///import sentencepiece as spm
        ///import numpy as np
        ///
        ///import sentencepiece as spm
        ///
        ///DATA_DIR = f&apos;en_fr/data&apos; 
        ///SP_DIR = f&apos;{DATA_DIR}/sp&apos;
        ///SRC_DIR = &apos;src&apos;
        ///TRG_DIR = &apos;trg&apos;
        ///SRC_RAW_DATA_NAME = &apos;raw_data.src&apos;
        ///TRG_RAW_DATA_NAME = &apos;raw_data.trg&apos;
        ///TRAIN_NAME = &apos;train.txt&apos;
        ///VALID_NAME = &apos;valid.txt&apos;
        ///TEST_NAME = &apos;test.txt&apos;
        ///
        ///pad_id = 0
        ///sos_id = 1
        ///eos_id = 2
        ///unk_id = 3
        ///src_model_prefix = &apos;src_sp&apos;
        ///trg_model_pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tokenizeddatapairs {
            get {
                return ResourceManager.GetString("tokenizeddatapairs", resourceCulture);
            }
        }
    }
}
