//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCaffe.db.temporal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DNNEntitiesTemporal : DbContext
    {
        public DNNEntitiesTemporal()
            : base("name=DNNEntitiesTemporal")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RawValue> RawValues { get; set; }
        public virtual DbSet<ValueItem> ValueItems { get; set; }
        public virtual DbSet<ValueStream> ValueStreams { get; set; }
    }
}
