//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCaffe.db.temporal
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawValue
    {
        public int ID { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public byte[] RawData { get; set; }
        public byte[] DataCriteria { get; set; }
        public byte[] DebugData { get; set; }
        public Nullable<byte> DebugDataFormatID { get; set; }
        public Nullable<byte> DataCriteriaFormatID { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
