//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace MyCaffe.test.automated
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TestingEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TestingEntities object using the connection string found in the 'TestingEntities' section of the application configuration file.
        /// </summary>
        public TestingEntities() : base("name=TestingEntities", "TestingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TestingEntities object.
        /// </summary>
        public TestingEntities(string connectionString) : base(connectionString, "TestingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TestingEntities object.
        /// </summary>
        public TestingEntities(EntityConnection connection) : base(connection, "TestingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Session> Sessions
        {
            get
            {
                if ((_Sessions == null))
                {
                    _Sessions = base.CreateObjectSet<Session>("Sessions");
                }
                return _Sessions;
            }
        }
        private ObjectSet<Session> _Sessions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Test> Tests
        {
            get
            {
                if ((_Tests == null))
                {
                    _Tests = base.CreateObjectSet<Test>("Tests");
                }
                return _Tests;
            }
        }
        private ObjectSet<Test> _Tests;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sessions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSessions(Session session)
        {
            base.AddObject("Sessions", session);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tests EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTests(Test test)
        {
            base.AddObject("Tests", test);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestingModel", Name="Session")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Session : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Session object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Session CreateSession(global::System.Int32 id)
        {
            Session session = new Session();
            session.ID = id;
            return session;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeStamp
        {
            get
            {
                return _TimeStamp;
            }
            set
            {
                OnTimeStampChanging(value);
                ReportPropertyChanging("TimeStamp");
                _TimeStamp = StructuralObject.SetValidValue(value, "TimeStamp");
                ReportPropertyChanged("TimeStamp");
                OnTimeStampChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeStamp;
        partial void OnTimeStampChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeStampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Session1
        {
            get
            {
                return _Session1;
            }
            set
            {
                OnSession1Changing(value);
                ReportPropertyChanging("Session1");
                _Session1 = StructuralObject.SetValidValue(value, true, "Session1");
                ReportPropertyChanged("Session1");
                OnSession1Changed();
            }
        }
        private global::System.String _Session1;
        partial void OnSession1Changing(global::System.String value);
        partial void OnSession1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TotalTestsRun
        {
            get
            {
                return _TotalTestsRun;
            }
            set
            {
                OnTotalTestsRunChanging(value);
                ReportPropertyChanging("TotalTestsRun");
                _TotalTestsRun = StructuralObject.SetValidValue(value, "TotalTestsRun");
                ReportPropertyChanged("TotalTestsRun");
                OnTotalTestsRunChanged();
            }
        }
        private Nullable<global::System.Int32> _TotalTestsRun;
        partial void OnTotalTestsRunChanging(Nullable<global::System.Int32> value);
        partial void OnTotalTestsRunChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TotalTestFailures
        {
            get
            {
                return _TotalTestFailures;
            }
            set
            {
                OnTotalTestFailuresChanging(value);
                ReportPropertyChanging("TotalTestFailures");
                _TotalTestFailures = StructuralObject.SetValidValue(value, "TotalTestFailures");
                ReportPropertyChanged("TotalTestFailures");
                OnTotalTestFailuresChanged();
            }
        }
        private Nullable<global::System.Int32> _TotalTestFailures;
        partial void OnTotalTestFailuresChanging(Nullable<global::System.Int32> value);
        partial void OnTotalTestFailuresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TestFailureRate
        {
            get
            {
                return _TestFailureRate;
            }
            set
            {
                OnTestFailureRateChanging(value);
                ReportPropertyChanging("TestFailureRate");
                _TestFailureRate = StructuralObject.SetValidValue(value, "TestFailureRate");
                ReportPropertyChanged("TestFailureRate");
                OnTestFailureRateChanged();
            }
        }
        private Nullable<global::System.Decimal> _TestFailureRate;
        partial void OnTestFailureRateChanging(Nullable<global::System.Decimal> value);
        partial void OnTestFailureRateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalTestTiming
        {
            get
            {
                return _TotalTestTiming;
            }
            set
            {
                OnTotalTestTimingChanging(value);
                ReportPropertyChanging("TotalTestTiming");
                _TotalTestTiming = StructuralObject.SetValidValue(value, "TotalTestTiming");
                ReportPropertyChanged("TotalTestTiming");
                OnTotalTestTimingChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalTestTiming;
        partial void OnTotalTestTimingChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalTestTimingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Path
        {
            get
            {
                return _Path;
            }
            set
            {
                OnPathChanging(value);
                ReportPropertyChanging("Path");
                _Path = StructuralObject.SetValidValue(value, true, "Path");
                ReportPropertyChanged("Path");
                OnPathChanged();
            }
        }
        private global::System.String _Path;
        partial void OnPathChanging(global::System.String value);
        partial void OnPathChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestingModel", Name="Test")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Test : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Test object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Test CreateTest(global::System.Int32 id)
        {
            Test test = new Test();
            test.ID = id;
            return test;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TestGroup
        {
            get
            {
                return _TestGroup;
            }
            set
            {
                OnTestGroupChanging(value);
                ReportPropertyChanging("TestGroup");
                _TestGroup = StructuralObject.SetValidValue(value, true, "TestGroup");
                ReportPropertyChanged("TestGroup");
                OnTestGroupChanged();
            }
        }
        private global::System.String _TestGroup;
        partial void OnTestGroupChanging(global::System.String value);
        partial void OnTestGroupChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TestMethod
        {
            get
            {
                return _TestMethod;
            }
            set
            {
                OnTestMethodChanging(value);
                ReportPropertyChanging("TestMethod");
                _TestMethod = StructuralObject.SetValidValue(value, true, "TestMethod");
                ReportPropertyChanged("TestMethod");
                OnTestMethodChanged();
            }
        }
        private global::System.String _TestMethod;
        partial void OnTestMethodChanging(global::System.String value);
        partial void OnTestMethodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Success
        {
            get
            {
                return _Success;
            }
            set
            {
                OnSuccessChanging(value);
                ReportPropertyChanging("Success");
                _Success = StructuralObject.SetValidValue(value, "Success");
                ReportPropertyChanged("Success");
                OnSuccessChanged();
            }
        }
        private Nullable<global::System.Boolean> _Success;
        partial void OnSuccessChanging(Nullable<global::System.Boolean> value);
        partial void OnSuccessChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ErrorString
        {
            get
            {
                return _ErrorString;
            }
            set
            {
                OnErrorStringChanging(value);
                ReportPropertyChanging("ErrorString");
                _ErrorString = StructuralObject.SetValidValue(value, true, "ErrorString");
                ReportPropertyChanged("ErrorString");
                OnErrorStringChanged();
            }
        }
        private global::System.String _ErrorString;
        partial void OnErrorStringChanging(global::System.String value);
        partial void OnErrorStringChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ErrorLocation
        {
            get
            {
                return _ErrorLocation;
            }
            set
            {
                OnErrorLocationChanging(value);
                ReportPropertyChanging("ErrorLocation");
                _ErrorLocation = StructuralObject.SetValidValue(value, true, "ErrorLocation");
                ReportPropertyChanged("ErrorLocation");
                OnErrorLocationChanged();
            }
        }
        private global::System.String _ErrorLocation;
        partial void OnErrorLocationChanging(global::System.String value);
        partial void OnErrorLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TestTiming
        {
            get
            {
                return _TestTiming;
            }
            set
            {
                OnTestTimingChanging(value);
                ReportPropertyChanging("TestTiming");
                _TestTiming = StructuralObject.SetValidValue(value, "TestTiming");
                ReportPropertyChanged("TestTiming");
                OnTestTimingChanged();
            }
        }
        private Nullable<global::System.Decimal> _TestTiming;
        partial void OnTestTimingChanging(Nullable<global::System.Decimal> value);
        partial void OnTestTimingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SessionID
        {
            get
            {
                return _SessionID;
            }
            set
            {
                OnSessionIDChanging(value);
                ReportPropertyChanging("SessionID");
                _SessionID = StructuralObject.SetValidValue(value, "SessionID");
                ReportPropertyChanged("SessionID");
                OnSessionIDChanged();
            }
        }
        private Nullable<global::System.Int32> _SessionID;
        partial void OnSessionIDChanging(Nullable<global::System.Int32> value);
        partial void OnSessionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Priority
        {
            get
            {
                return _Priority;
            }
            set
            {
                OnPriorityChanging(value);
                ReportPropertyChanging("Priority");
                _Priority = StructuralObject.SetValidValue(value, "Priority");
                ReportPropertyChanged("Priority");
                OnPriorityChanged();
            }
        }
        private Nullable<global::System.Int32> _Priority;
        partial void OnPriorityChanging(Nullable<global::System.Int32> value);
        partial void OnPriorityChanged();

        #endregion

    }

    #endregion

}
