//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCaffe.db.image
{
    using System;
    using System.Collections.Generic;
    
    public partial class Label
    {
        public int ID { get; set; }
        public Nullable<int> Label1 { get; set; }
        public string Name { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> ImageCount { get; set; }
        public Nullable<int> ActiveLabel { get; set; }
    }
}
