//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCaffe.db.image
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawImageResult
    {
        public int ID { get; set; }
        public Nullable<int> Idx { get; set; }
        public Nullable<int> Label { get; set; }
        public Nullable<int> ResultCount { get; set; }
        public byte[] Results { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public byte[] ExtraData { get; set; }
        public Nullable<int> BatchCount { get; set; }
    }
}
