//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCaffe.db.image
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawImageGroup
    {
        public int ID { get; set; }
        public Nullable<int> Idx { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Property1 { get; set; }
        public Nullable<decimal> Property2 { get; set; }
        public Nullable<decimal> Property3 { get; set; }
        public Nullable<decimal> Property4 { get; set; }
        public Nullable<decimal> Property5 { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public byte[] RawData { get; set; }
    }
}
