//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCaffe.db.image
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawImageParameter
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public byte[] Value { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> RawImageID { get; set; }
        public string TextValue { get; set; }
    }
}
