//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCaffe.db.image
{
    using System;
    using System.Collections.Generic;
    
    public partial class Source
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ImageHeight { get; set; }
        public Nullable<int> ImageWidth { get; set; }
        public Nullable<int> ImageChannels { get; set; }
        public Nullable<bool> ImageEncoded { get; set; }
        public Nullable<int> ImageCount { get; set; }
        public string OwnerID { get; set; }
        public Nullable<bool> SaveImagesToFile { get; set; }
        public Nullable<int> CopyOfSourceID { get; set; }
    }
}
